package com.geovnn.meteoapuane.domain.models

import android.graphics.Bitmap

data class WebcamPage(
    val massaCentro: Bitmap? = null,
    val moncigoli: Bitmap? = null,
    val canevara: Bitmap? = null,
    val monteBorla: Bitmap? = null,
    val vinca: Bitmap? = null,
    val marinaDiMassa: Bitmap? = null,
    val marinaDiCarrara: Bitmap? = null,
    val avenza: Bitmap? = null,
    val fivizzano: Bitmap? = null,
    val villafrancaLunigiana: Bitmap? = null,
    val bagnone: Bitmap? = null,
    val sassalbo: Bitmap? = null,
    val monteBosta: Bitmap? = null,
    val zumZeri: Bitmap? = null,
    val passoDelCerreto1: Bitmap? = null,
    val passoDelCerreto2: Bitmap? = null,
    val cerretoLaghi: Bitmap? = null,
    val rigoso: Bitmap? = null,
    val pratospilla1: Bitmap? = null,
    val pratospilla2: Bitmap? = null,
    val monteCusna: Bitmap? = null,
    val lagoSanto: Bitmap? = null,
    val valditacca: Bitmap? = null,
    val trefiumi: Bitmap? = null,
    val borgoValDiTaro: Bitmap? = null,
    val ghiareDiBerceto: Bitmap? = null,
    val ponzanoMagra: Bitmap? = null,
    val boccaDiMagra: Bitmap? = null,
    val lerici: Bitmap? = null,
    val portovenere: Bitmap? = null,
    val sestaGodano: Bitmap? = null,
    val vareseLigure: Bitmap? = null,
    val pietrasanta: Bitmap? = null,
    val lidoDiCamaiore1: Bitmap? = null,
    val lidoDiCamaiore2: Bitmap? = null,
    val viareggio: Bitmap? = null,
    val capanneDiCareggine: Bitmap? = null,
    val monteArgegna: Bitmap? = null,
)
