package com.geovnn.meteoapuane.domain.models

data class WebcamPage(
    val massaCentro: String = "",
    val moncigoli: String = "",
    val canevara: String = "",
    val monteBorla: String = "",
    val vinca: String = "",
    val marinaDiMassa: String = "",
    val marinaDiCarrara: String = "",
    val avenza: String = "",
    val fivizzano: String = "",
    val villafrancaLunigiana: String = "",
    val bagnone: String = "",
    val sassalbo: String = "",
    val monteBosta: String = "",
    val zumZeri: String = "",
    val passoDelCerreto1: String = "",
    val passoDelCerreto2: String = "",
    val cerretoLaghi: String = "",
    val rigoso: String = "",
    val pratospilla1: String = "",
    val pratospilla2: String = "",
    val monteCusna: String = "",
    val lagoSanto: String = "",
    val valditacca: String = "",
    val trefiumi: String = "",
    val borgoValDiTaro: String = "",
    val ghiareDiBerceto: String = "",
    val ponzanoMagra: String = "",
    val boccaDiMagra: String = "",
    val lerici: String = "",
    val portovenere: String = "",
    val sestaGodano: String = "",
    val vareseLigure: String = "",
    val pietrasanta: String = "",
    val lidoDiCamaiore1: String = "",
    val lidoDiCamaiore2: String = "",
    val viareggio: String = "",
    val capanneDiCareggine: String = "",
    val monteArgegna: String = "",
)
